apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-10-04T15:07:46Z"
  generation: 1
  labels:
    access: s3
  name: outsider
  namespace: bd-outsider
  resourceVersion: "1597"
  uid: 0f9c5329-ce37-47d3-8faa-5d0d2724ea66
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: trunglizabeth/s3lab@sha256:b9e7cf4d42d76b3c6e238ba4c4163bab5324ade9160ca4b5cd826d6bdcfabe93
    imagePullPolicy: IfNotPresent
    name: outsider
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rzjsn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-bigdata-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-rzjsn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-10-04T15:07:48Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-10-04T15:07:46Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-10-04T15:07:48Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-10-04T15:07:48Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-10-04T15:07:46Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://460cbda33d1b502232e1a97d4d5f40b82e8fcadde72d1efd2bb7a3b6d3cc3521
    image: sha256:f5093ecd7ae2562e9239e93343c26936560cc447dc81d6e9e5448134fac43726
    imageID: docker.io/trunglizabeth/s3lab@sha256:b9e7cf4d42d76b3c6e238ba4c4163bab5324ade9160ca4b5cd826d6bdcfabe93
    lastState: {}
    name: outsider
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-10-04T15:07:47Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rzjsn
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.20.0.3
  hostIPs:
  - ip: 172.20.0.3
  observedGeneration: 1
  phase: Running
  podIP: 10.42.0.16
  podIPs:
  - ip: 10.42.0.16
  qosClass: BestEffort
  startTime: "2026-10-04T15:07:46Z"
