apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: quota-positive
  name: quota-positive
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  containers:
  - image: trunglizabeth/s3lab@sha256:b9e7cf4d42d76b3c6e238ba4c4163bab5324ade9160ca4b5cd826d6bdcfabe93
    name: quota-positive
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
