apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"object-data","namespace":"bd-g01"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"4Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k3d-bigdata-server-0
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2026-10-03T17:16:54Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: object-data
  namespace: bd-g01
  resourceVersion: "5711"
  uid: 1a30965d-a990-4b7b-b3f8-f04dabd36f3e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-1a30965d-a990-4b7b-b3f8-f04dabd36f3e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  phase: Bound
