apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"team-budget","namespace":"bd-g01"},"spec":{"hard":{"limits.cpu":"4","limits.memory":"4Gi","persistentvolumeclaims":"2","pods":"10","requests.cpu":"2","requests.memory":"2Gi","requests.storage":"8Gi"}}}
    creationTimestamp: "2026-10-02T14:35:34Z"
    name: team-budget
    namespace: bd-g01
    resourceVersion: "6832"
    uid: c6fb53c5-2461-4c59-9308-0601224e31e9
  spec:
    hard:
      limits.cpu: "4"
      limits.memory: 4Gi
      persistentvolumeclaims: "2"
      pods: "10"
      requests.cpu: "2"
      requests.memory: 2Gi
      requests.storage: 8Gi
  status:
    hard:
      limits.cpu: "4"
      limits.memory: 4Gi
      persistentvolumeclaims: "2"
      pods: "10"
      requests.cpu: "2"
      requests.memory: 2Gi
      requests.storage: 8Gi
    used:
      limits.cpu: "0"
      limits.memory: "0"
      persistentvolumeclaims: "0"
      pods: "0"
      requests.cpu: "0"
      requests.memory: "0"
      requests.storage: "0"
kind: List
metadata:
  resourceVersion: ""
