apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"team-budget","namespace":"bd-g01"},"spec":{"hard":{"limits.cpu":"4","limits.memory":"4Gi","persistentvolumeclaims":"2","pods":"10","requests.cpu":"2","requests.memory":"2Gi","requests.storage":"8Gi"}}}
  creationTimestamp: "2026-10-04T14:33:37Z"
  name: team-budget
  namespace: bd-g01
  resourceVersion: "849"
  uid: e9a45b2b-747f-4447-9a84-61bce7448054
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: 8Gi
status:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: 8Gi
  used:
    limits.cpu: "0"
    limits.memory: "0"
    persistentvolumeclaims: "0"
    pods: "0"
    requests.cpu: "0"
    requests.memory: "0"
    requests.storage: "0"
